# Generated by Django 3.0.3 on 2020-03-16 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_Id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('user_account', models.CharField(max_length=20)),
                ('user_name', models.CharField(max_length=20)),
                ('user_password', models.CharField(max_length=20)),
            ],
        ),
    ]
